package:
  format-version: "1.0.0"
  name: "bootloader"
  type: "api"
  status: "production"
  required: false
  version: "3.6.0"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "dev"
    - name: "csp"
      type: "package"
      version: "dev"
    - name: "core"
      type: "package"
      version: "dev"
    - name: "net"
      type: "package"
      version: "v3.10.1"
    - name: "usb"
      type: "package"
      version: "dev"